<?php

$ADDRESS_CHECKSUM_LENGTH = 4;
$ADDRESS_HASH_LENGTH = 20;

return [
    'ADDRESS_VERSION' => 1,
    'ADDRESS_CHECKSUM_LENGTH' => $ADDRESS_CHECKSUM_LENGTH,
    'ADDRESS_HASH_LENGTH' => $ADDRESS_HASH_LENGTH,
    'ADDRESS_LENGTH' => 1 + 1 + $ADDRESS_CHECKSUM_LENGTH + $ADDRESS_HASH_LENGTH,
];